### ISSUE TITLE
Fork button on goshdarnclosuresyntax doesn't resolve

### ISSUE THREAD

**Issue by jkaufman** [ZevEisenberg/fuckingclosuresyntax.com#10]
The GitHub fork button on http://goshdarnclosuresyntax.com doesn't resolve. The fork button on http://fuckingclosuresyntax.com works fine.

**Comment by ZevEisenberg** [comment]
This is on iOS Safari. Oddly, I can 3D Touch the link and get the page to open, but it doesn't work if I just tap the link. Must be something to do with the Hover redirect, which actually just uses an iframe embed.
