### ISSUE TITLE
Update for Swift 3 syntax

### ISSUE THREAD

**Issue by ZevEisenberg** [ZevEisenberg/fuckingclosuresyntax.com#14]
I just noticed that some things could be tweaked a bit for Swift 3. For example,

```swift
array.sort({ (item1, item2) in return item1 < item2 })
```

would become:

```swift
array.sort(by: { (item1, item2) in return item1 < item2 })
```

Small difference, but probably worth updating.

**Comment by capnslipp** [comment]
More pertinently, the current syntax on fuckingclosuresyntax.com doesn't compile in Swift 3.  So as it currently stands, what's up on fuckingclosuresyntax.com is bad information for Swift newbies.

Also, the Swift 3 equivalent of `array.sort(…) -> [Element]` would be `array.sorted(by: …) -> [Element]`.  Swift 3's `sort(by: …) -> Void` mutates the array in-place.

**Comment by capnslipp** [comment]
I believe this issue can be closed now.

**Comment by ZevEisenberg** [comment]
It can, although I'm going to remove the parentheses from `-> (ReturnType)` expressions. They're redundant.

**Comment by capnslipp** [comment]
I agree.  The parens shouldn't be there.
