### ISSUE TITLE
Can't access fuckingclosuresyntax.com

### ISSUE THREAD

**Issue by michaelbnd** [ZevEisenberg/fuckingclosuresyntax.com#19]
Hey Zev, I see that fuckingclosuresyntax.com is down, do you still own the domain?

**Comment by ZevEisenberg** [comment]
Thanks for the heads up! I missed an email on Friday about the domain renewal failing. I've renewed it; fortunately it wasn't sniped in the interim! It should be back up soon.

**Comment by michaelbnd** [comment]
It's back already!
